version: "3.8"

services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - src/.env

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file:
      - src/.env
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - src/.env
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 10s
      retries: 5

  app:
    container_name: app
    build: .
    restart: on-failure
    command: bash -c "alembic upgrade head && cd src && gunicorn -c /code/gunicorn/gunicorn.conf.py main:app"
    expose:
      - 5000
    env_file:
      - src/.env
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
      - rabbitmq
      - db

volumes:
  postgres_data:
  pgadmin-data:
  rabbitmq: