version: "3.8"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - src/.env

  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - src/.env
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 10s
      retries: 5

  app:
    build: .
    restart: on-failure
    command: ["/code/docker/app.sh"]
    container_name: fastapi_app
    ports:
      - 80:80
    env_file:
      - src/.env
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq: